version: "1"

services:
  app:
    command: >
      sh -c "python3 manage.py migrate &
             python3 manage.py createsuperuser --noinput --phone 11111 --email admin@admin.com
             python3 manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image : postgres:12.0-alpine
    volumes:
      - postgress_data:/app
    environment:
      - POSTGRES_USER=Maksik
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=test_shop_db
    ports:
      - "5432:5432"

  redis:
    image : redis:alpine
  celer:
    restart: always
    build:
      context: .
    command: >
      sh -c "celery -A shop worker -l info"
    volumes:
      - ./app
    depends_on:
      - db
      - app
      - redis
volumes:
  postgres_data:




