# Generated by Django 4.1.4 on 2022-12-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashback',
            options={'ordering': ['percent']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['percent']},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name_plural': 'Producer'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['count_on_stock', 'price'], 'verbose_name_plural': 'ProductItem'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['expire_date']},
        ),
        migrations.AlterField(
            model_name='productitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discount'),
        ),
    ]
