# Generated by Django 4.1.4 on 2023-01-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_basket_number_of_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='title',
            new_name='name',
        ),
    ]
