# Generated by Django 4.1.4 on 2023-01-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='descrition',
            new_name='description',
        ),
    ]
